// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/sftp.dart';
import 'api/simple.dart';
import 'api/ssh.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  SshConfig dco_decode_box_autoadd_ssh_config(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SftpEntry> dco_decode_list_sftp_entry(dynamic raw);

  @protected
  List<TerminalChunk> dco_decode_list_terminal_chunk(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  SessionPhase dco_decode_session_phase(dynamic raw);

  @protected
  SessionStatus dco_decode_session_status(dynamic raw);

  @protected
  SftpDirectoryListing dco_decode_sftp_directory_listing(dynamic raw);

  @protected
  SftpEntry dco_decode_sftp_entry(dynamic raw);

  @protected
  SftpEntryType dco_decode_sftp_entry_type(dynamic raw);

  @protected
  SshConfig dco_decode_ssh_config(dynamic raw);

  @protected
  TcpProbeResult dco_decode_tcp_probe_result(dynamic raw);

  @protected
  TerminalChunk dco_decode_terminal_chunk(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  SshConfig sse_decode_box_autoadd_ssh_config(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SftpEntry> sse_decode_list_sftp_entry(SseDeserializer deserializer);

  @protected
  List<TerminalChunk> sse_decode_list_terminal_chunk(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  SessionPhase sse_decode_session_phase(SseDeserializer deserializer);

  @protected
  SessionStatus sse_decode_session_status(SseDeserializer deserializer);

  @protected
  SftpDirectoryListing sse_decode_sftp_directory_listing(
    SseDeserializer deserializer,
  );

  @protected
  SftpEntry sse_decode_sftp_entry(SseDeserializer deserializer);

  @protected
  SftpEntryType sse_decode_sftp_entry_type(SseDeserializer deserializer);

  @protected
  SshConfig sse_decode_ssh_config(SseDeserializer deserializer);

  @protected
  TcpProbeResult sse_decode_tcp_probe_result(SseDeserializer deserializer);

  @protected
  TerminalChunk sse_decode_terminal_chunk(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ssh_config(
    SshConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sftp_entry(
    List<SftpEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_terminal_chunk(
    List<TerminalChunk> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_session_phase(SessionPhase self, SseSerializer serializer);

  @protected
  void sse_encode_session_status(SessionStatus self, SseSerializer serializer);

  @protected
  void sse_encode_sftp_directory_listing(
    SftpDirectoryListing self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sftp_entry(SftpEntry self, SseSerializer serializer);

  @protected
  void sse_encode_sftp_entry_type(SftpEntryType self, SseSerializer serializer);

  @protected
  void sse_encode_ssh_config(SshConfig self, SseSerializer serializer);

  @protected
  void sse_encode_tcp_probe_result(
    TcpProbeResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_terminal_chunk(TerminalChunk self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
