// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/sftp.dart';
import 'api/simple.dart';
import 'api/ssh.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1025336713;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_terminal',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiSimpleAppName();

  int crateApiSftpCreateSftpSession();

  int crateApiSshCreateSshSession();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<String> crateApiSftpSftpConnect({
    required int sessionId,
    required SshConfig config,
  });

  void crateApiSftpSftpCreateDir({
    required int sessionId,
    required String path,
  });

  void crateApiSftpSftpDeletePath({
    required int sessionId,
    required String path,
    required bool isDir,
  });

  void crateApiSftpSftpDisconnect({required int sessionId});

  void crateApiSftpSftpDisposeSession({required int sessionId});

  void crateApiSftpSftpDownloadFile({
    required int sessionId,
    required String remotePath,
    required String localPath,
  });

  String crateApiSftpSftpFileName({required String path});

  SftpDirectoryListing crateApiSftpSftpListDir({
    required int sessionId,
    String? path,
  });

  String crateApiSftpSftpSuggestDownloadPath({required String fileName});

  void crateApiSftpSftpUploadFile({
    required int sessionId,
    required String localPath,
    required String remotePath,
  });

  Future<void> crateApiSshSshConnect({
    required int sessionId,
    required SshConfig config,
    required int cols,
    required int rows,
  });

  void crateApiSshSshDisconnect({required int sessionId});

  void crateApiSshSshDisposeSession({required int sessionId});

  SessionStatus crateApiSshSshGetStatus({required int sessionId});

  TcpProbeResult crateApiSshSshProbeTcp({
    required String host,
    required int port,
  });

  List<TerminalChunk> crateApiSshSshReadOutput({required int sessionId});

  void crateApiSshSshResize({
    required int sessionId,
    required int cols,
    required int rows,
  });

  void crateApiSshSshSendInput({required int sessionId, required String input});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiSimpleAppName() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleAppNameConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAppNameConstMeta =>
      const TaskConstMeta(debugName: "app_name", argNames: []);

  @override
  int crateApiSftpCreateSftpSession() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSftpCreateSftpSessionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpCreateSftpSessionConstMeta =>
      const TaskConstMeta(debugName: "create_sftp_session", argNames: []);

  @override
  int crateApiSshCreateSshSession() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSshCreateSshSessionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshCreateSshSessionConstMeta =>
      const TaskConstMeta(debugName: "create_ssh_session", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<String> crateApiSftpSftpConnect({
    required int sessionId,
    required SshConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(sessionId, serializer);
          sse_encode_box_autoadd_ssh_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSftpSftpConnectConstMeta,
        argValues: [sessionId, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpConnectConstMeta => const TaskConstMeta(
    debugName: "sftp_connect",
    argNames: ["sessionId", "config"],
  );

  @override
  void crateApiSftpSftpCreateDir({
    required int sessionId,
    required String path,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(sessionId, serializer);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSftpSftpCreateDirConstMeta,
        argValues: [sessionId, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpCreateDirConstMeta => const TaskConstMeta(
    debugName: "sftp_create_dir",
    argNames: ["sessionId", "path"],
  );

  @override
  void crateApiSftpSftpDeletePath({
    required int sessionId,
    required String path,
    required bool isDir,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(sessionId, serializer);
          sse_encode_String(path, serializer);
          sse_encode_bool(isDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSftpSftpDeletePathConstMeta,
        argValues: [sessionId, path, isDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpDeletePathConstMeta => const TaskConstMeta(
    debugName: "sftp_delete_path",
    argNames: ["sessionId", "path", "isDir"],
  );

  @override
  void crateApiSftpSftpDisconnect({required int sessionId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(sessionId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSftpSftpDisconnectConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpDisconnectConstMeta => const TaskConstMeta(
    debugName: "sftp_disconnect",
    argNames: ["sessionId"],
  );

  @override
  void crateApiSftpSftpDisposeSession({required int sessionId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(sessionId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSftpSftpDisposeSessionConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpDisposeSessionConstMeta =>
      const TaskConstMeta(
        debugName: "sftp_dispose_session",
        argNames: ["sessionId"],
      );

  @override
  void crateApiSftpSftpDownloadFile({
    required int sessionId,
    required String remotePath,
    required String localPath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(sessionId, serializer);
          sse_encode_String(remotePath, serializer);
          sse_encode_String(localPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSftpSftpDownloadFileConstMeta,
        argValues: [sessionId, remotePath, localPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpDownloadFileConstMeta =>
      const TaskConstMeta(
        debugName: "sftp_download_file",
        argNames: ["sessionId", "remotePath", "localPath"],
      );

  @override
  String crateApiSftpSftpFileName({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSftpSftpFileNameConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpFileNameConstMeta =>
      const TaskConstMeta(debugName: "sftp_file_name", argNames: ["path"]);

  @override
  SftpDirectoryListing crateApiSftpSftpListDir({
    required int sessionId,
    String? path,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(sessionId, serializer);
          sse_encode_opt_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sftp_directory_listing,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSftpSftpListDirConstMeta,
        argValues: [sessionId, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpListDirConstMeta => const TaskConstMeta(
    debugName: "sftp_list_dir",
    argNames: ["sessionId", "path"],
  );

  @override
  String crateApiSftpSftpSuggestDownloadPath({required String fileName}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(fileName, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSftpSftpSuggestDownloadPathConstMeta,
        argValues: [fileName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpSuggestDownloadPathConstMeta =>
      const TaskConstMeta(
        debugName: "sftp_suggest_download_path",
        argNames: ["fileName"],
      );

  @override
  void crateApiSftpSftpUploadFile({
    required int sessionId,
    required String localPath,
    required String remotePath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(sessionId, serializer);
          sse_encode_String(localPath, serializer);
          sse_encode_String(remotePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSftpSftpUploadFileConstMeta,
        argValues: [sessionId, localPath, remotePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpUploadFileConstMeta => const TaskConstMeta(
    debugName: "sftp_upload_file",
    argNames: ["sessionId", "localPath", "remotePath"],
  );

  @override
  Future<void> crateApiSshSshConnect({
    required int sessionId,
    required SshConfig config,
    required int cols,
    required int rows,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(sessionId, serializer);
          sse_encode_box_autoadd_ssh_config(config, serializer);
          sse_encode_u_32(cols, serializer);
          sse_encode_u_32(rows, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSshSshConnectConstMeta,
        argValues: [sessionId, config, cols, rows],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshSshConnectConstMeta => const TaskConstMeta(
    debugName: "ssh_connect",
    argNames: ["sessionId", "config", "cols", "rows"],
  );

  @override
  void crateApiSshSshDisconnect({required int sessionId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(sessionId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSshSshDisconnectConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshSshDisconnectConstMeta =>
      const TaskConstMeta(debugName: "ssh_disconnect", argNames: ["sessionId"]);

  @override
  void crateApiSshSshDisposeSession({required int sessionId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(sessionId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSshSshDisposeSessionConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshSshDisposeSessionConstMeta =>
      const TaskConstMeta(
        debugName: "ssh_dispose_session",
        argNames: ["sessionId"],
      );

  @override
  SessionStatus crateApiSshSshGetStatus({required int sessionId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(sessionId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSshSshGetStatusConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshSshGetStatusConstMeta =>
      const TaskConstMeta(debugName: "ssh_get_status", argNames: ["sessionId"]);

  @override
  TcpProbeResult crateApiSshSshProbeTcp({
    required String host,
    required int port,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tcp_probe_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSshSshProbeTcpConstMeta,
        argValues: [host, port],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshSshProbeTcpConstMeta => const TaskConstMeta(
    debugName: "ssh_probe_tcp",
    argNames: ["host", "port"],
  );

  @override
  List<TerminalChunk> crateApiSshSshReadOutput({required int sessionId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(sessionId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_terminal_chunk,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSshSshReadOutputConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshSshReadOutputConstMeta => const TaskConstMeta(
    debugName: "ssh_read_output",
    argNames: ["sessionId"],
  );

  @override
  void crateApiSshSshResize({
    required int sessionId,
    required int cols,
    required int rows,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(sessionId, serializer);
          sse_encode_u_32(cols, serializer);
          sse_encode_u_32(rows, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSshSshResizeConstMeta,
        argValues: [sessionId, cols, rows],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshSshResizeConstMeta => const TaskConstMeta(
    debugName: "ssh_resize",
    argNames: ["sessionId", "cols", "rows"],
  );

  @override
  void crateApiSshSshSendInput({
    required int sessionId,
    required String input,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(sessionId, serializer);
          sse_encode_String(input, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSshSshSendInputConstMeta,
        argValues: [sessionId, input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshSshSendInputConstMeta => const TaskConstMeta(
    debugName: "ssh_send_input",
    argNames: ["sessionId", "input"],
  );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  SshConfig dco_decode_box_autoadd_ssh_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ssh_config(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SftpEntry> dco_decode_list_sftp_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_sftp_entry).toList();
  }

  @protected
  List<TerminalChunk> dco_decode_list_terminal_chunk(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_terminal_chunk).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  SessionPhase dco_decode_session_phase(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SessionPhase.values[raw as int];
  }

  @protected
  SessionStatus dco_decode_session_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SessionStatus(
      phase: dco_decode_session_phase(arr[0]),
      message: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  SftpDirectoryListing dco_decode_sftp_directory_listing(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SftpDirectoryListing(
      path: dco_decode_String(arr[0]),
      entries: dco_decode_list_sftp_entry(arr[1]),
    );
  }

  @protected
  SftpEntry dco_decode_sftp_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return SftpEntry(
      name: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      entryType: dco_decode_sftp_entry_type(arr[2]),
      size: dco_decode_u_64(arr[3]),
      modifiedUnix: dco_decode_opt_box_autoadd_u_64(arr[4]),
      permissions: dco_decode_String(arr[5]),
    );
  }

  @protected
  SftpEntryType dco_decode_sftp_entry_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SftpEntryType.values[raw as int];
  }

  @protected
  SshConfig dco_decode_ssh_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SshConfig(
      host: dco_decode_String(arr[0]),
      port: dco_decode_u_16(arr[1]),
      username: dco_decode_String(arr[2]),
      password: dco_decode_opt_String(arr[3]),
      privateKey: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  TcpProbeResult dco_decode_tcp_probe_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TcpProbeResult(
      reachable: dco_decode_bool(arr[0]),
      message: dco_decode_String(arr[1]),
      latencyMs: dco_decode_opt_box_autoadd_u_32(arr[2]),
    );
  }

  @protected
  TerminalChunk dco_decode_terminal_chunk(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TerminalChunk(
      data: dco_decode_String(arr[0]),
      isError: dco_decode_bool(arr[1]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  SshConfig sse_decode_box_autoadd_ssh_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ssh_config(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SftpEntry> sse_decode_list_sftp_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SftpEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_sftp_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<TerminalChunk> sse_decode_list_terminal_chunk(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TerminalChunk>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_terminal_chunk(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SessionPhase sse_decode_session_phase(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SessionPhase.values[inner];
  }

  @protected
  SessionStatus sse_decode_session_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_phase = sse_decode_session_phase(deserializer);
    var var_message = sse_decode_opt_String(deserializer);
    return SessionStatus(phase: var_phase, message: var_message);
  }

  @protected
  SftpDirectoryListing sse_decode_sftp_directory_listing(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_entries = sse_decode_list_sftp_entry(deserializer);
    return SftpDirectoryListing(path: var_path, entries: var_entries);
  }

  @protected
  SftpEntry sse_decode_sftp_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_entryType = sse_decode_sftp_entry_type(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    var var_modifiedUnix = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_permissions = sse_decode_String(deserializer);
    return SftpEntry(
      name: var_name,
      path: var_path,
      entryType: var_entryType,
      size: var_size,
      modifiedUnix: var_modifiedUnix,
      permissions: var_permissions,
    );
  }

  @protected
  SftpEntryType sse_decode_sftp_entry_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SftpEntryType.values[inner];
  }

  @protected
  SshConfig sse_decode_ssh_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_host = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_username = sse_decode_String(deserializer);
    var var_password = sse_decode_opt_String(deserializer);
    var var_privateKey = sse_decode_opt_String(deserializer);
    return SshConfig(
      host: var_host,
      port: var_port,
      username: var_username,
      password: var_password,
      privateKey: var_privateKey,
    );
  }

  @protected
  TcpProbeResult sse_decode_tcp_probe_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_reachable = sse_decode_bool(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_latencyMs = sse_decode_opt_box_autoadd_u_32(deserializer);
    return TcpProbeResult(
      reachable: var_reachable,
      message: var_message,
      latencyMs: var_latencyMs,
    );
  }

  @protected
  TerminalChunk sse_decode_terminal_chunk(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_data = sse_decode_String(deserializer);
    var var_isError = sse_decode_bool(deserializer);
    return TerminalChunk(data: var_data, isError: var_isError);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_ssh_config(
    SshConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ssh_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_sftp_entry(
    List<SftpEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_sftp_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_terminal_chunk(
    List<TerminalChunk> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_terminal_chunk(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_session_phase(SessionPhase self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_session_status(SessionStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_session_phase(self.phase, serializer);
    sse_encode_opt_String(self.message, serializer);
  }

  @protected
  void sse_encode_sftp_directory_listing(
    SftpDirectoryListing self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_list_sftp_entry(self.entries, serializer);
  }

  @protected
  void sse_encode_sftp_entry(SftpEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_sftp_entry_type(self.entryType, serializer);
    sse_encode_u_64(self.size, serializer);
    sse_encode_opt_box_autoadd_u_64(self.modifiedUnix, serializer);
    sse_encode_String(self.permissions, serializer);
  }

  @protected
  void sse_encode_sftp_entry_type(
    SftpEntryType self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_ssh_config(SshConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.username, serializer);
    sse_encode_opt_String(self.password, serializer);
    sse_encode_opt_String(self.privateKey, serializer);
  }

  @protected
  void sse_encode_tcp_probe_result(
    TcpProbeResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.reachable, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_opt_box_autoadd_u_32(self.latencyMs, serializer);
  }

  @protected
  void sse_encode_terminal_chunk(TerminalChunk self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.data, serializer);
    sse_encode_bool(self.isError, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
