// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'ssh.dart';

// These functions are ignored because they are not marked as `pub`: `authenticate`, `get_sftp_session`, `join_remote_path`, `new`, `sftp_registry`, `with_active_session`, `write_private_key`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ActiveSftpSession`, `ClientHandler`, `SftpSessionHandle`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `check_server_key`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

int createSftpSession() => RustLib.instance.api.crateApiSftpCreateSftpSession();

Future<String> sftpConnect({
  required int sessionId,
  required SshConfig config,
}) => RustLib.instance.api.crateApiSftpSftpConnect(
  sessionId: sessionId,
  config: config,
);

SftpDirectoryListing sftpListDir({required int sessionId, String? path}) =>
    RustLib.instance.api.crateApiSftpSftpListDir(
      sessionId: sessionId,
      path: path,
    );

void sftpDownloadFile({
  required int sessionId,
  required String remotePath,
  required String localPath,
}) => RustLib.instance.api.crateApiSftpSftpDownloadFile(
  sessionId: sessionId,
  remotePath: remotePath,
  localPath: localPath,
);

void sftpUploadFile({
  required int sessionId,
  required String localPath,
  required String remotePath,
}) => RustLib.instance.api.crateApiSftpSftpUploadFile(
  sessionId: sessionId,
  localPath: localPath,
  remotePath: remotePath,
);

void sftpCreateDir({required int sessionId, required String path}) => RustLib
    .instance
    .api
    .crateApiSftpSftpCreateDir(sessionId: sessionId, path: path);

void sftpDeletePath({
  required int sessionId,
  required String path,
  required bool isDir,
}) => RustLib.instance.api.crateApiSftpSftpDeletePath(
  sessionId: sessionId,
  path: path,
  isDir: isDir,
);

void sftpDisconnect({required int sessionId}) =>
    RustLib.instance.api.crateApiSftpSftpDisconnect(sessionId: sessionId);

void sftpDisposeSession({required int sessionId}) =>
    RustLib.instance.api.crateApiSftpSftpDisposeSession(sessionId: sessionId);

String sftpSuggestDownloadPath({required String fileName}) => RustLib
    .instance
    .api
    .crateApiSftpSftpSuggestDownloadPath(fileName: fileName);

String sftpFileName({required String path}) =>
    RustLib.instance.api.crateApiSftpSftpFileName(path: path);

class SftpDirectoryListing {
  final String path;
  final List<SftpEntry> entries;

  const SftpDirectoryListing({required this.path, required this.entries});

  @override
  int get hashCode => path.hashCode ^ entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SftpDirectoryListing &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          entries == other.entries;
}

class SftpEntry {
  final String name;
  final String path;
  final SftpEntryType entryType;
  final BigInt size;
  final BigInt? modifiedUnix;
  final String permissions;

  const SftpEntry({
    required this.name,
    required this.path,
    required this.entryType,
    required this.size,
    this.modifiedUnix,
    required this.permissions,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      entryType.hashCode ^
      size.hashCode ^
      modifiedUnix.hashCode ^
      permissions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SftpEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          entryType == other.entryType &&
          size == other.size &&
          modifiedUnix == other.modifiedUnix &&
          permissions == other.permissions;
}

enum SftpEntryType { file, directory, symlink, other }
