// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `authenticate`, `error`, `get_session`, `log_step`, `new`, `probe_ssh_banner`, `push_output`, `registry`, `run_session`, `set_status`, `write_private_key`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SessionCommand`, `SshSessionHandle`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `check_server_key`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

int createSshSession() => RustLib.instance.api.crateApiSshCreateSshSession();

Future<void> sshConnect({
  required int sessionId,
  required SshConfig config,
  required int cols,
  required int rows,
}) => RustLib.instance.api.crateApiSshSshConnect(
  sessionId: sessionId,
  config: config,
  cols: cols,
  rows: rows,
);

void sshSendInput({required int sessionId, required String input}) => RustLib
    .instance
    .api
    .crateApiSshSshSendInput(sessionId: sessionId, input: input);

void sshResize({
  required int sessionId,
  required int cols,
  required int rows,
}) => RustLib.instance.api.crateApiSshSshResize(
  sessionId: sessionId,
  cols: cols,
  rows: rows,
);

List<TerminalChunk> sshReadOutput({required int sessionId}) =>
    RustLib.instance.api.crateApiSshSshReadOutput(sessionId: sessionId);

SessionStatus sshGetStatus({required int sessionId}) =>
    RustLib.instance.api.crateApiSshSshGetStatus(sessionId: sessionId);

void sshDisconnect({required int sessionId}) =>
    RustLib.instance.api.crateApiSshSshDisconnect(sessionId: sessionId);

void sshDisposeSession({required int sessionId}) =>
    RustLib.instance.api.crateApiSshSshDisposeSession(sessionId: sessionId);

TcpProbeResult sshProbeTcp({required String host, required int port}) =>
    RustLib.instance.api.crateApiSshSshProbeTcp(host: host, port: port);

enum SessionPhase { disconnected, connecting, authenticating, connected, error }

class SessionStatus {
  final SessionPhase phase;
  final String? message;

  const SessionStatus({required this.phase, this.message});

  @override
  int get hashCode => phase.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionStatus &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          message == other.message;
}

class SshConfig {
  final String host;
  final int port;
  final String username;
  final String? password;
  final String? privateKey;

  const SshConfig({
    required this.host,
    required this.port,
    required this.username,
    this.password,
    this.privateKey,
  });

  @override
  int get hashCode =>
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      password.hashCode ^
      privateKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SshConfig &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          password == other.password &&
          privateKey == other.privateKey;
}

class TcpProbeResult {
  final bool reachable;
  final String message;
  final int? latencyMs;

  const TcpProbeResult({
    required this.reachable,
    required this.message,
    this.latencyMs,
  });

  @override
  int get hashCode =>
      reachable.hashCode ^ message.hashCode ^ latencyMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TcpProbeResult &&
          runtimeType == other.runtimeType &&
          reachable == other.reachable &&
          message == other.message &&
          latencyMs == other.latencyMs;
}

class TerminalChunk {
  final String data;
  final bool isError;

  const TerminalChunk({required this.data, required this.isError});

  @override
  int get hashCode => data.hashCode ^ isError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TerminalChunk &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          isError == other.isError;
}
